# Generated by Django 5.2.3 on 2025-06-30 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año')),
                ('sinopsis', models.TextField(blank=True, null=True, verbose_name='Sinopsis')),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la imagen')),
                ('hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'ordering': ['-hora_creacion'],
            },
        ),
    ]
