# Generated by Django 3.2.25 on 2025-06-26 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-hora_creacion']},
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='texto',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la imagen'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='sinopsis',
            field=models.TextField(blank=True, null=True, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='hora_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada el'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
    ]
